// Normalize whatever the backend stores ("English", "en", "Spanish", "es", …)
export function normalizeLang(raw) {
  if (!raw) return 'en'
  const map = {
    english: 'en', spanish: 'es', french: 'fr',
    mandarin: 'zh', chinese: 'zh', arabic: 'ar',
    portuguese: 'pt', german: 'de', japanese: 'ja',
    korean: 'ko', hindi: 'hi',
  }
  const lower = raw.toLowerCase()
  return map[lower] ?? lower
}

const T = {
  // ── Navigation / actions ──────────────────────────────────────────────────
  sign_in:        { en: 'Sign in',        es: 'Iniciar sesión',     fr: 'Se connecter',     zh: '登录',       ar: 'تسجيل الدخول',    pt: 'Entrar',            de: 'Anmelden',        ja: 'ログイン',          ko: '로그인',           hi: 'साइन इन करें' },
  sign_out:       { en: 'Sign out',       es: 'Cerrar sesión',      fr: 'Se déconnecter',   zh: '退出登录',    ar: 'تسجيل الخروج',    pt: 'Sair',              de: 'Abmelden',        ja: 'ログアウト',        ko: '로그아웃',         hi: 'साइन आउट करें' },
  get_started:    { en: 'Get started',    es: 'Comenzar',           fr: 'Commencer',        zh: '开始使用',    ar: 'ابدأ الآن',       pt: 'Começar',           de: 'Loslegen',        ja: '始める',            ko: '시작하기',         hi: 'शुरू करें' },
  continue:       { en: 'Continue',       es: 'Continuar',          fr: 'Continuer',        zh: '继续',       ar: 'متابعة',           pt: 'Continuar',         de: 'Weiter',          ja: '続ける',            ko: '계속',             hi: 'जारी रखें' },
  back:           { en: '← Back',         es: '← Atrás',           fr: '← Retour',         zh: '← 返回',    ar: '← رجوع',          pt: '← Voltar',          de: '← Zurück',        ja: '← 戻る',           ko: '← 뒤로',           hi: '← वापस' },
  go_home:        { en: 'Go home',        es: 'Ir al inicio',       fr: "Retour à l'accueil", zh: '返回首页',  ar: 'الصفحة الرئيسية', pt: 'Ir para início',    de: 'Zur Startseite',  ja: 'ホームへ',          ko: '홈으로',           hi: 'होम पर जाएं' },
  download:       { en: 'Download',       es: 'Descargar',          fr: 'Télécharger',      zh: '下载',       ar: 'تنزيل',            pt: 'Baixar',            de: 'Herunterladen',   ja: 'ダウンロード',      ko: '다운로드',         hi: 'डाउनलोड करें' },
  download_json:  { en: 'Download JSON',  es: 'Descargar JSON',     fr: 'Télécharger JSON', zh: '下载 JSON',  ar: 'تنزيل JSON',       pt: 'Baixar JSON',       de: 'JSON herunterladen', ja: 'JSON ダウンロード', ko: 'JSON 다운로드',    hi: 'JSON डाउनलोड करें' },

  // ── Auth ─────────────────────────────────────────────────────────────────
  sign_in_subtitle:    { en: 'Sign in to your account',   es: 'Inicia sesión en tu cuenta',    fr: 'Connectez-vous à votre compte',   zh: '登录您的账户',   ar: 'سجّل دخولك إلى حسابك',    pt: 'Entre na sua conta',             de: 'Bei Ihrem Konto anmelden',        ja: 'アカウントにログイン',             ko: '계정에 로그인',              hi: 'अपने खाते में साइन इन करें' },
  create_account:      { en: 'Create account',            es: 'Crear cuenta',                  fr: 'Créer un compte',                 zh: '创建账户',       ar: 'إنشاء حساب',               pt: 'Criar conta',                    de: 'Konto erstellen',                 ja: 'アカウント作成',                   ko: '계정 만들기',                hi: 'खाता बनाएं' },
  create_account_sub:  { en: 'Create your account',       es: 'Crea tu cuenta',                fr: 'Créez votre compte',              zh: '创建您的账户',   ar: 'أنشئ حسابك',               pt: 'Crie sua conta',                 de: 'Erstellen Sie Ihr Konto',         ja: 'アカウントを作成',                 ko: '계정을 만드세요',            hi: 'अपना खाता बनाएं' },
  email:               { en: 'Email',                     es: 'Correo electrónico',            fr: 'E-mail',                          zh: '电子邮件',       ar: 'البريد الإلكتروني',         pt: 'E-mail',                         de: 'E-Mail',                          ja: 'メールアドレス',                   ko: '이메일',                    hi: 'ईमेल' },
  password:            { en: 'Password',                  es: 'Contraseña',                    fr: 'Mot de passe',                    zh: '密码',           ar: 'كلمة المرور',               pt: 'Senha',                          de: 'Passwort',                        ja: 'パスワード',                       ko: '비밀번호',                  hi: 'पासवर्ड' },
  full_name:           { en: 'Full name',                 es: 'Nombre completo',               fr: 'Nom complet',                     zh: '全名',           ar: 'الاسم الكامل',              pt: 'Nome completo',                  de: 'Vollständiger Name',              ja: 'フルネーム',                       ko: '전체 이름',                 hi: 'पूरा नाम' },
  phone_number:        { en: 'Phone number',              es: 'Número de teléfono',            fr: 'Numéro de téléphone',             zh: '电话号码',       ar: 'رقم الهاتف',                pt: 'Número de telefone',             de: 'Telefonnummer',                   ja: '電話番号',                         ko: '전화번호',                  hi: 'फ़ोन नंबर' },
  phone_hint:          { en: 'Include country code, e.g. +1', es: 'Incluye el código de país, p. ej. +1', fr: 'Incluez l\'indicatif, ex. +1', zh: '请包含国家代码，如 +1', ar: 'أدرج رمز الدولة، مثل +1', pt: 'Inclua o código do país, ex. +1', de: 'Ländervorwahl angeben, z. B. +1', ja: '国番号を含めてください（例：+1）',  ko: '국가 코드 포함, 예: +1',     hi: 'देश कोड शामिल करें, जैसे +1' },
  recovery_email:      { en: 'Recovery email',            es: 'Correo de recuperación',        fr: 'E-mail de récupération',          zh: '恢复邮箱',       ar: 'بريد الاسترداد',            pt: 'E-mail de recuperação',          de: 'Wiederherstellungs-E-Mail',       ja: '回復用メール',                     ko: '복구 이메일',               hi: 'रिकवरी ईमेल' },
  optional:            { en: '(optional)',                es: '(opcional)',                    fr: '(facultatif)',                    zh: '（可选）',       ar: '(اختياري)',                 pt: '(opcional)',                     de: '(optional)',                      ja: '（任意）',                         ko: '(선택)',                    hi: '(वैकल्पिक)' },
  preferred_language:  { en: 'Preferred language',        es: 'Idioma preferido',              fr: 'Langue préférée',                 zh: '首选语言',       ar: 'اللغة المفضلة',             pt: 'Idioma preferido',               de: 'Bevorzugte Sprache',              ja: '使用言語',                         ko: '선호 언어',                 hi: 'पसंदीदा भाषा' },
  signing_in:          { en: 'Signing in…',               es: 'Iniciando sesión…',             fr: 'Connexion…',                      zh: '登录中…',        ar: 'جار تسجيل الدخول…',        pt: 'Entrando…',                      de: 'Anmelden…',                       ja: 'ログイン中…',                      ko: '로그인 중…',                hi: 'साइन इन हो रहा है…' },
  sending_code:        { en: 'Sending code…',             es: 'Enviando código…',              fr: 'Envoi du code…',                  zh: '发送验证码…',    ar: 'جار إرسال الرمز…',          pt: 'Enviando código…',               de: 'Code senden…',                    ja: 'コード送信中…',                    ko: '코드 전송 중…',             hi: 'कोड भेजा जा रहा है…' },
  verifying:           { en: 'Verifying…',                es: 'Verificando…',                  fr: 'Vérification…',                   zh: '验证中…',        ar: 'جار التحقق…',               pt: 'Verificando…',                   de: 'Verifizieren…',                   ja: '確認中…',                          ko: '확인 중…',                  hi: 'सत्यापित हो रहा है…' },
  verify_create:       { en: 'Verify & create account',  es: 'Verificar y crear cuenta',      fr: 'Vérifier et créer le compte',     zh: '验证并创建账户', ar: 'تحقق وأنشئ الحساب',         pt: 'Verificar e criar conta',        de: 'Verifizieren & Konto erstellen',  ja: '確認してアカウント作成',            ko: '확인 및 계정 만들기',       hi: 'सत्यापित करें और खाता बनाएं' },
  no_account:          { en: "Don't have an account?",   es: '¿No tienes cuenta?',            fr: 'Pas de compte ?',                 zh: '没有账户？',     ar: 'ليس لديك حساب؟',            pt: 'Não tem uma conta?',             de: 'Noch kein Konto?',                ja: 'アカウントがありませんか？',        ko: '계정이 없으신가요?',        hi: 'खाता नहीं है?' },
  have_account:        { en: 'Already have an account?', es: '¿Ya tienes cuenta?',            fr: 'Vous avez déjà un compte ?',      zh: '已有账户？',     ar: 'هل لديك حساب بالفعل؟',      pt: 'Já tem uma conta?',              de: 'Bereits ein Konto?',              ja: 'すでにアカウントをお持ちですか？',  ko: '이미 계정이 있으신가요?',   hi: 'पहले से खाता है?' },
  create_one:          { en: 'Create one',               es: 'Crear una',                     fr: 'En créer un',                     zh: '创建一个',       ar: 'إنشاء حساب',                pt: 'Criar uma',                      de: 'Erstellen',                       ja: '作成する',                         ko: '만들기',                    hi: 'बनाएं' },
  account_created:     { en: 'Account created! Sign in to continue.', es: '¡Cuenta creada! Inicia sesión para continuar.', fr: 'Compte créé ! Connectez-vous pour continuer.', zh: '账户已创建！请登录继续。', ar: 'تم إنشاء الحساب! سجّل دخولك للمتابعة.', pt: 'Conta criada! Entre para continuar.', de: 'Konto erstellt! Melden Sie sich an.', ja: 'アカウントを作成しました！続けるにはログインしてください。', ko: '계정이 생성되었습니다! 계속하려면 로그인하세요.', hi: 'खाता बना दिया गया! जारी रखने के लिए साइन इन करें।' },

  // ── Verification ──────────────────────────────────────────────────────────
  code_sent_to:       { en: 'We sent a 6-digit code to',          es: 'Enviamos un código de 6 dígitos a',   fr: 'Nous avons envoyé un code à 6 chiffres à', zh: '我们已向以下地址发送了6位验证码',  ar: 'أرسلنا رمزًا من 6 أرقام إلى',  pt: 'Enviamos um código de 6 dígitos para', de: 'Wir haben einen 6-stelligen Code gesendet an', ja: '6桁のコードを送信しました：', ko: '6자리 코드를 보냈습니다:', hi: 'हमने 6 अंकों का कोड भेजा' },
  code_delay:         { en: 'The code may take 30 seconds to arrive. Please be patient.', es: 'El código puede tardar 30 segundos. Por favor, sé paciente.', fr: 'Le code peut prendre 30 secondes. Soyez patient.', zh: '验证码最多需要30秒到达，请耐心等待。', ar: 'قد يستغرق وصول الرمز 30 ثانية. يُرجى الانتظار.', pt: 'O código pode demorar 30 segundos. Por favor, aguarde.', de: 'Der Code kann bis zu 30 Sekunden dauern. Bitte warten.', ja: 'コードの受信に最大30秒かかる場合があります。', ko: '코드가 도착하는 데 30초 걸릴 수 있습니다.', hi: 'कोड आने में 30 सेकंड लग सकते हैं।' },
  verification_code:  { en: 'Verification code',                   es: 'Código de verificación',              fr: 'Code de vérification',                     zh: '验证码',                              ar: 'رمز التحقق',                     pt: 'Código de verificação',               de: 'Verifizierungscode',                   ja: '確認コード',                          ko: '인증 코드',                  hi: 'सत्यापन कोड' },

  // ── Profile ───────────────────────────────────────────────────────────────
  loading_profile:  { en: 'Loading your profile…',  es: 'Cargando tu perfil…',      fr: 'Chargement du profil…',   zh: '加载个人资料…',    ar: 'جار تحميل ملفك الشخصي…',  pt: 'Carregando perfil…',        de: 'Profil wird geladen…',    ja: 'プロフィールを読み込み中…',   ko: '프로필 로딩 중…',          hi: 'प्रोफ़ाइल लोड हो रही है…' },
  university:       { en: 'University',             es: 'Universidad',              fr: 'Université',              zh: '大学',             ar: 'الجامعة',                  pt: 'Universidade',              de: 'Universität',             ja: '大学',                        ko: '대학교',                   hi: 'विश्वविद्यालय' },
  school_code:      { en: 'School code',            es: 'Código de la escuela',     fr: 'Code école',              zh: '学校代码',         ar: 'رمز المدرسة',               pt: 'Código da escola',          de: 'Schulcode',               ja: '学校コード',                  ko: '학교 코드',                hi: 'स्कूल कोड' },
  account_id:       { en: 'Account ID',             es: 'ID de cuenta',             fr: 'ID de compte',            zh: '账户 ID',          ar: 'معرّف الحساب',              pt: 'ID da conta',               de: 'Konto-ID',                ja: 'アカウント ID',               ko: '계정 ID',                  hi: 'खाता ID' },
  my_documents:     { en: 'My documents',           es: 'Mis documentos',           fr: 'Mes documents',           zh: '我的文档',         ar: 'مستنداتي',                  pt: 'Meus documentos',           de: 'Meine Dokumente',         ja: '自分のドキュメント',          ko: '내 문서',                  hi: 'मेरे दस्तावेज़' },

  // ── Contract gallery ──────────────────────────────────────────────────────
  no_documents:     { en: 'No documents yet.',          es: 'Aún no hay documentos.',         fr: 'Aucun document.',                 zh: '暂无文档。',          ar: 'لا توجد مستندات بعد.',         pt: 'Nenhum documento ainda.',         de: 'Noch keine Dokumente.',         ja: 'まだドキュメントがありません。', ko: '문서가 없습니다.',             hi: 'अभी कोई दस्तावेज़ नहीं।' },
  upload_first:     { en: 'Upload your first PDF',      es: 'Sube tu primer PDF',             fr: 'Téléversez votre premier PDF',    zh: '上传您的第一个 PDF',   ar: 'ارفع ملف PDF الأول',            pt: 'Envie seu primeiro PDF',          de: 'Erste PDF hochladen',           ja: '最初のPDFをアップロード',    ko: '첫 번째 PDF 업로드',          hi: 'अपना पहला PDF अपलोड करें' },
  upload_pdf:       { en: '+ Upload PDF',               es: '+ Subir PDF',                    fr: '+ Téléverser un PDF',             zh: '+ 上传 PDF',          ar: '+ رفع PDF',                     pt: '+ Enviar PDF',                    de: '+ PDF hochladen',               ja: '+ PDF アップロード',         ko: '+ PDF 업로드',                hi: '+ PDF अपलोड करें' },
  profile:          { en: 'Profile',                    es: 'Perfil',                         fr: 'Profil',                          zh: '个人资料',            ar: 'الملف الشخصي',                  pt: 'Perfil',                          de: 'Profil',                        ja: 'プロフィール',               ko: '프로필',                      hi: 'प्रोफ़ाइल' },
  hover_tooltips:   { en: 'Hover tooltips',             es: 'Mostrar pistas',                 fr: 'Infobulles',                      zh: '悬停提示',            ar: 'تلميحات التمرير',               pt: 'Dicas ao passar o mouse',         de: 'Tooltips beim Hover',           ja: 'ホバーヒント',               ko: '마우스 오버 툴팁',            hi: 'होवर टूलटिप्स' },
  analysis:         { en: 'Analysis',                   es: 'Análisis',                       fr: 'Analyse',                         zh: '分析',                ar: 'التحليل',                       pt: 'Análise',                         de: 'Analyse',                       ja: '分析',                       ko: '분석',                        hi: 'विश्लेषण' },
  raw_json:         { en: 'Raw JSON',                   es: 'JSON sin procesar',              fr: 'JSON brut',                       zh: '原始 JSON',           ar: 'JSON الخام',                    pt: 'JSON bruto',                      de: 'Rohes JSON',                    ja: '生 JSON',                    ko: '원본 JSON',                   hi: 'कच्चा JSON' },

  // ── Contract upload ───────────────────────────────────────────────────────
  parse_contract:  { en: 'Parse Contract PDF',   es: 'Analizar PDF del contrato',  fr: 'Analyser le PDF du contrat',  zh: '解析合同 PDF',   ar: 'تحليل ملف PDF للعقد',      pt: 'Analisar PDF do contrato',    de: 'Vertrags-PDF analysieren',   ja: '契約PDFを解析',              ko: '계약 PDF 분석',              hi: 'अनुबंध PDF पार्स करें' },
  pdf_file:        { en: 'PDF file',             es: 'Archivo PDF',                fr: 'Fichier PDF',                 zh: 'PDF 文件',       ar: 'ملف PDF',                   pt: 'Arquivo PDF',                 de: 'PDF-Datei',                  ja: 'PDFファイル',                ko: 'PDF 파일',                   hi: 'PDF फ़ाइल' },
  upload_parse:    { en: 'Upload & Parse',       es: 'Subir y analizar',           fr: 'Téléverser et analyser',      zh: '上传并解析',     ar: 'رفع وتحليل',                pt: 'Enviar e analisar',           de: 'Hochladen & Analysieren',    ja: 'アップロードして解析',        ko: '업로드 및 분석',             hi: 'अपलोड और पार्स करें' },
  parsing:         { en: 'Parsing…',             es: 'Analizando…',                fr: 'Analyse…',                    zh: '解析中…',        ar: 'جار التحليل…',              pt: 'Analisando…',                 de: 'Analysieren…',               ja: '解析中…',                    ko: '분석 중…',                   hi: 'पार्स हो रहा है…' },
  extracted_text:  { en: 'Extracted text',       es: 'Texto extraído',             fr: 'Texte extrait',               zh: '提取的文本',     ar: 'النص المستخرج',             pt: 'Texto extraído',              de: 'Extrahierter Text',          ja: '抽出されたテキスト',          ko: '추출된 텍스트',              hi: 'निकाला गया पाठ' },

  // ── Analysis panel ────────────────────────────────────────────────────────
  eta_min:         { en: '~{n} min to fill',     es: '~{n} min para rellenar',     fr: '~{n} min à remplir',          zh: '约 {n} 分钟填写', ar: '~{n} دقيقة للملء',          pt: '~{n} min para preencher',     de: '~{n} Min. zum Ausfüllen',    ja: '記入時間 約{n}分',           ko: '작성 ~{n}분',                hi: 'भरने में ~{n} मिनट' },
  before_begin:    { en: 'Before you begin',     es: 'Antes de empezar',           fr: 'Avant de commencer',          zh: '开始之前',       ar: 'قبل البدء',                 pt: 'Antes de começar',            de: 'Bevor Sie beginnen',         ja: '始める前に',                 ko: '시작하기 전에',              hi: 'शुरू करने से पहले' },
  steps:           { en: 'Steps',                es: 'Pasos',                      fr: 'Étapes',                      zh: '步骤',           ar: 'الخطوات',                   pt: 'Passos',                      de: 'Schritte',                   ja: 'ステップ',                   ko: '단계',                       hi: 'चरण' },
  notes:           { en: 'Notes',                es: 'Notas',                      fr: 'Notes',                       zh: '注释',           ar: 'ملاحظات',                   pt: 'Notas',                       de: 'Notizen',                    ja: 'メモ',                       ko: '메모',                       hi: 'नोट्स' },
  page:            { en: 'Page',                 es: 'Página',                     fr: 'Page',                        zh: '第',             ar: 'الصفحة',                    pt: 'Página',                      de: 'Seite',                      ja: 'ページ',                     ko: '페이지',                     hi: 'पृष्ठ' },

  // ── Home ──────────────────────────────────────────────────────────────────
  wip_banner:      { en: 'Web version — work in progress. The full FormFriend experience is on iOS.', es: 'Versión web en desarrollo. La experiencia completa está en iOS.', fr: 'Version web en développement. L\'expérience complète est sur iOS.', zh: '网页版本正在开发中。完整体验请使用 iOS 应用。', ar: 'الإصدار الويب قيد التطوير. التجربة الكاملة على iOS.', pt: 'Versão web em desenvolvimento. A experiência completa está no iOS.', de: 'Webversion in Entwicklung. Das vollständige Erlebnis ist auf iOS.', ja: 'Web版は開発中です。完全なFormFriendの体験はiOSでご利用ください。', ko: '웹 버전 — 개발 중입니다. 전체 FormFriend 경험은 iOS에서 제공됩니다.', hi: 'वेब संस्करण — कार्य प्रगति पर है। पूरा FormFriend अनुभव iOS पर है।' },
  ios_badge:       { en: 'Primary app on iOS — web preview available', es: 'App principal en iOS — vista previa web disponible', fr: 'App principale sur iOS — aperçu web disponible', zh: '主应用在 iOS 上 — 网页预览可用', ar: 'التطبيق الأساسي على iOS — معاينة الويب متاحة', pt: 'App principal no iOS — pré-visualização web disponível', de: 'Haupt-App auf iOS — Webvorschau verfügbar', ja: 'メインアプリはiOS — ウェブプレビュー利用可能', ko: 'iOS 기본 앱 — 웹 미리보기 사용 가능', hi: 'मुख्य ऐप iOS पर — वेब प्रीव्यू उपलब्ध' },
  hero_line1:      { en: 'Navigate any document,', es: 'Navega cualquier documento,', fr: 'Naviguez dans n\'importe quel document,', zh: '导航任何文档，', ar: 'تصفّح أي مستند،', pt: 'Navegue em qualquer documento,', de: 'Navigieren Sie durch jedes Dokument,', ja: 'どんな書類も、', ko: '모든 문서를 탐색하세요,', hi: 'किसी भी दस्तावेज़ को नेविगेट करें,' },
  hero_line2:      { en: 'step by step.', es: 'paso a paso.', fr: 'étape par étape.', zh: '逐步完成。', ar: 'خطوة بخطوة.', pt: 'passo a passo.', de: 'Schritt für Schritt.', ja: 'ステップバイステップで。', ko: '단계별로.', hi: 'कदम दर कदम।' },
  hero_sub:        { en: 'FormFriend uses AI and OCR to guide you through complex forms — highlighting exactly where to sign, what to fill, and what to prepare.', es: 'FormFriend usa IA y OCR para guiarte en formularios complejos, resaltando dónde firmar, qué rellenar y qué preparar.', fr: "FormFriend utilise l'IA et l'OCR pour vous guider — indiquant où signer, quoi remplir et quoi préparer.", zh: 'FormFriend 使用 AI 和 OCR 引导您完成复杂表格，精确标注签名位置、填写内容及所需准备。', ar: 'يستخدم FormFriend الذكاء الاصطناعي والتعرف الضوئي لإرشادك خلال النماذج المعقدة.', pt: 'FormFriend usa IA e OCR para guiá-lo em formulários complexos — destacando onde assinar, o que preencher e o que preparar.', de: 'FormFriend nutzt KI und OCR, um Sie durch komplexe Formulare zu führen — mit Hervorhebung wo Sie unterschreiben, was Sie ausfüllen und was Sie vorbereiten müssen.', ja: 'FormFriendはAIとOCRを使用して複雑なフォームをガイドします。署名箇所、記入内容、準備物を正確にハイライトします。', ko: 'FormFriend는 AI와 OCR을 사용하여 복잡한 양식을 안내합니다 — 서명 위치, 작성 내용, 준비물을 정확히 강조합니다.', hi: 'FormFriend जटिल फॉर्म में मार्गदर्शन के लिए AI और OCR का उपयोग करता है — हस्ताक्षर, भरने और तैयारी की जगह को हाइलाइट करता है।' },
  try_preview:     { en: 'Try the web preview', es: 'Probar la versión web', fr: 'Essayer la version web', zh: '试用网页预览', ar: 'جرّب معاينة الويب', pt: 'Experimentar a versão web', de: 'Webvorschau ausprobieren', ja: 'ウェブプレビューを試す', ko: '웹 미리보기 사용해보기', hi: 'वेब प्रीव्यू आज़माएं' },
  ios_feat_title:  { en: 'iOS App — Core Features', es: 'App iOS — Funciones principales', fr: 'App iOS — Fonctionnalités principales', zh: 'iOS 应用 — 核心功能', ar: 'تطبيق iOS — الميزات الأساسية', pt: 'App iOS — Funcionalidades principais', de: 'iOS-App — Kernfunktionen', ja: 'iOSアプリ — 主な機能', ko: 'iOS 앱 — 핵심 기능', hi: 'iOS ऐप — मुख्य सुविधाएं' },
  feat_scan:       { en: 'Scan any document',      es: 'Escanea cualquier documento', fr: 'Scannez n\'importe quel document', zh: '扫描任何文档', ar: 'امسح أي مستند ضوئيًا', pt: 'Digitalize qualquer documento', de: 'Beliebiges Dokument scannen', ja: 'どんな書類もスキャン', ko: '모든 문서 스캔', hi: 'कोई भी दस्तावेज़ स्कैन करें' },
  feat_scan_sub:   { en: 'Capture multi-page forms with your camera. No scanner needed.', es: 'Captura formularios de varias páginas con tu cámara. Sin escáner.', fr: 'Capturez des formulaires multi-pages avec votre appareil. Sans scanner.', zh: '用摄像头拍摄多页表格，无需扫描仪。', ar: 'التقط نماذج متعددة الصفحات بكاميرتك. لا حاجة لماسح ضوئي.', pt: 'Capture formulários de várias páginas com sua câmera. Sem scanner.', de: 'Mehrseitige Formulare mit der Kamera aufnehmen. Kein Scanner nötig.', ja: 'カメラで複数ページのフォームを撮影。スキャナー不要。', ko: '카메라로 다중 페이지 양식 캡처. 스캐너 불필요.', hi: 'कैमरे से बहु-पृष्ठ फॉर्म कैप्चर करें। कोई स्कैनर नहीं चाहिए।' },
  feat_ocr:        { en: 'AI-powered OCR',         es: 'OCR con inteligencia artificial', fr: 'OCR par IA', zh: 'AI 驱动的 OCR', ar: 'تعرف ضوئي بالذكاء الاصطناعي', pt: 'OCR com IA', de: 'KI-gestützte Texterkennung', ja: 'AI搭載OCR', ko: 'AI 기반 OCR', hi: 'AI-संचालित OCR' },
  feat_ocr_sub:    { en: 'AWS Textract extracts every field with precise bounding boxes for live highlighting.', es: 'AWS Textract extrae cada campo con cuadros delimitadores precisos.', fr: 'AWS Textract extrait chaque champ avec des zones précises pour la mise en évidence.', zh: 'AWS Textract 精确提取每个字段，实现实时高亮显示。', ar: 'يستخرج AWS Textract كل حقل بصناديق تحديد دقيقة للإبراز الفوري.', pt: 'O AWS Textract extrai cada campo com caixas delimitadoras precisas para destaque em tempo real.', de: 'AWS Textract extrahiert jedes Feld mit präzisen Bounding Boxes für Live-Hervorhebung.', ja: 'AWS Textractが精密なバウンディングボックスで各フィールドを抽出し、リアルタイムハイライトを実現。', ko: 'AWS Textract가 정밀한 경계 상자로 모든 필드를 추출하여 실시간 강조 표시를 제공합니다.', hi: 'AWS Textract लाइव हाइलाइटिंग के लिए सटीक बाउंडिंग बॉक्स के साथ हर फ़ील्ड निकालता है।' },
  feat_guide:      { en: 'Step-by-step guidance',  es: 'Guía paso a paso', fr: 'Guidage étape par étape', zh: '逐步引导', ar: 'إرشاد خطوة بخطوة', pt: 'Orientação passo a passo', de: 'Schritt-für-Schritt-Anleitung', ja: 'ステップバイステップのガイダンス', ko: '단계별 안내', hi: 'चरण-दर-चरण मार्गदर्शन' },
  feat_guide_sub:  { en: 'Each field is highlighted in the PDF in order, with clear instructions for what to write.', es: 'Cada campo se resalta en orden en el PDF con instrucciones claras.', fr: 'Chaque champ est mis en évidence dans le PDF avec des instructions claires.', zh: '每个字段按顺序在 PDF 中高亮显示，并附有清晰的填写说明。', ar: 'يتم تمييز كل حقل بالترتيب في PDF مع تعليمات واضحة.', pt: 'Cada campo é destacado no PDF em ordem, com instruções claras sobre o que escrever.', de: 'Jedes Feld wird im PDF der Reihe nach hervorgehoben, mit klaren Anweisungen zum Ausfüllen.', ja: 'PDFの各フィールドが順番にハイライトされ、記入内容の明確な指示が表示されます。', ko: 'PDF의 각 필드가 순서대로 강조되며, 무엇을 쓸지 명확한 지침이 제공됩니다.', hi: 'PDF में प्रत्येक फ़ील्ड क्रमशः हाइलाइट की जाती है, जिसमें लिखने के बारे में स्पष्ट निर्देश होते हैं।' },
  feat_lang:       { en: 'Multilingual',            es: 'Multilingüe', fr: 'Multilingue', zh: '多语言支持', ar: 'متعدد اللغات', pt: 'Multilíngue', de: 'Mehrsprachig', ja: '多言語対応', ko: '다국어', hi: 'बहुभाषी' },
  feat_lang_sub:   { en: 'Full guidance in English, Spanish, French, Mandarin, and Arabic.', es: 'Guía completa en inglés, español, francés, mandarín y árabe.', fr: 'Guidage complet en anglais, espagnol, français, mandarin et arabe.', zh: '完整支持英语、西班牙语、法语、普通话和阿拉伯语。', ar: 'إرشاد كامل بالإنجليزية والإسبانية والفرنسية والماندرين والعربية.', pt: 'Orientação completa em inglês, espanhol, francês, mandarim e árabe.', de: 'Vollständige Anleitung auf Englisch, Spanisch, Französisch, Mandarin und Arabisch.', ja: '英語、スペイン語、フランス語、中国語、アラビア語で完全なガイダンスを提供。', ko: '영어, 스페인어, 프랑스어, 중국어, 아랍어로 완전한 안내를 제공합니다.', hi: 'अंग्रेज़ी, स्पेनिश, फ्रेंच, मंदारिन और अरबी में पूर्ण मार्गदर्शन।' },
  about_web_title: { en: 'About this web version', es: 'Sobre la versión web', fr: 'À propos de la version web', zh: '关于此网页版本', ar: 'حول هذا الإصدار الويب', pt: 'Sobre esta versão web', de: 'Über diese Webversion', ja: 'このウェブ版について', ko: '이 웹 버전에 대하여', hi: 'इस वेब संस्करण के बारे में' },
  about_web_body:  { en: "This web interface lets you upload PDFs, run AI analysis, and review guided results from any browser. It's a work in progress — the full guided overlay, live camera scanning, and offline support are in the iOS app.", es: 'Esta interfaz web te permite subir PDFs, ejecutar análisis de IA y revisar resultados guiados desde cualquier navegador. Es una versión preliminar — la superposición guiada completa, el escaneo con cámara y el soporte offline están en la app iOS.', fr: "Cette interface web vous permet de téléverser des PDF, d'exécuter une analyse IA et de consulter les résultats guidés depuis n'importe quel navigateur. C'est une version préliminaire — la superposition guidée complète, la numérisation par caméra et le support hors ligne sont dans l'app iOS.", zh: '此网页界面让您可以上传 PDF、运行 AI 分析并在任何浏览器中查看引导结果。这是一个正在开发中的版本——完整的引导叠加层、实时摄像头扫描和离线支持均在 iOS 应用中。', ar: 'تتيح لك هذه الواجهة الويب رفع ملفات PDF وتشغيل تحليل الذكاء الاصطناعي ومراجعة النتائج الموجّهة من أي متصفح. هذا إصدار تجريبي — التراكب الموجّه الكامل ومسح الكاميرا الحي والدعم دون اتصال موجودة في تطبيق iOS.', pt: 'Esta interface web permite carregar PDFs, executar análise de IA e revisar resultados guiados em qualquer navegador. É uma versão em desenvolvimento — a sobreposição guiada completa, digitalização ao vivo e suporte offline estão no app iOS.', de: 'Diese Weboberfläche ermöglicht das Hochladen von PDFs, KI-Analysen und die Überprüfung geführter Ergebnisse in jedem Browser. Es ist noch in Entwicklung — die vollständige geführte Überlagerung, Live-Kamera-Scan und Offline-Unterstützung sind in der iOS-App.', ja: 'このウェブインターフェースでPDFのアップロード、AI分析の実行、ガイド付き結果の確認が任意のブラウザから可能です。開発中のため、完全なガイドオーバーレイ、ライブカメラスキャン、オフラインサポートはiOSアプリにあります。', ko: '이 웹 인터페이스를 통해 모든 브라우저에서 PDF를 업로드하고 AI 분석을 실행하며 안내된 결과를 검토할 수 있습니다. 개발 중인 버전으로 — 전체 안내 오버레이, 실시간 카메라 스캔, 오프라인 지원은 iOS 앱에 있습니다.', hi: 'यह वेब इंटरफ़ेस किसी भी ब्राउज़र से PDF अपलोड करने, AI विश्लेषण चलाने और निर्देशित परिणाम देखने की सुविधा देता है। यह विकास में है — पूर्ण गाइडेड ओवरले, लाइव कैमरा स्कैनिंग और ऑफलाइन समर्थन iOS ऐप में हैं।' },
  footer:          { en: 'FormFriend · Built at YHacks 2026', es: 'FormFriend · Creado en YHacks 2026', fr: 'FormFriend · Créé à YHacks 2026', zh: 'FormFriend · 于 YHacks 2026 构建', ar: 'FormFriend · تم بناؤه في YHacks 2026', pt: 'FormFriend · Construído no YHacks 2026', de: 'FormFriend · Entwickelt beim YHacks 2026', ja: 'FormFriend · YHacks 2026 で制作', ko: 'FormFriend · YHacks 2026에서 제작', hi: 'FormFriend · YHacks 2026 में बनाया गया' },
}

export function t(lang, key, vars = {}) {
  const row = T[key]
  if (!row) return key
  let str = row[lang] ?? row['en'] ?? key
  for (const [k, v] of Object.entries(vars)) {
    str = str.replace(`{${k}}`, String(v))
  }
  return str
}
