import SwiftUI
import Combine
class LanguageManager: ObservableObject {
    static let shared = LanguageManager()
    
    @AppStorage("preferredLanguage") var currentLanguage: String = "English"
    
    private let translations: [String: [String: String]] = [
        "Spanish": [
            "Account Security": "Seguridad de la cuenta",
            "Account details": "Detalles de la cuenta",
            "Action Steps": "Pasos a seguir",
            "App Settings": "Ajustes de la aplicación",
            "Begin Scan": "Comenzar escaneo",
            "Cancel": "Cancelar",
            "Captured Image": "Imagen capturada",
            "Change Password Placeholder": "Cambiar contraseña",
            "Confirm & Login": "Confirmar e iniciar sesión",
            "Continue": "Continuar",
            "Create Account": "Crear cuenta",
            "Document Complete!": "¡Documento completado!",
            "Documents": "Documentos",
            "Don't have an account? Sign Up": "¿No tienes cuenta? Regístrate",
            "Done": "Hecho",
            "English": "Inglés",
            "Spanish": "Español",
            "French": "Francés",
            "Mandarin": "Mandarín",
            "Arabic": "Árabe",
            "Executing Analysis...": "Ejecutando análisis...",
            "Extracted Text": "Texto extraído",
            "FormFriend": "FormFriend",
            "Get Started": "Comenzar",
            "Government Form • 3 Pages": "Formulario del gobierno • 3 Páginas",
            "Guided View": "Vista guiada",
            "Help & FAQ Placeholder": "Ayuda y preguntas frecuentes",
            "Line up the page inside the frame": "Alinee la página dentro del marco",
            "Log In": "Iniciar sesión",
            "Log Out": "Cerrar sesión",
            "Log in to FormFriend to continue": "Inicia sesión en FormFriend para continuar",
            "Make sure the amount listed in Box 1 matches your final pay stub for the year.": "Asegúrese de que el monto indicado en la casilla 1 coincida con su último recibo de pago del año.",
            "Next Step": "Próximo paso",
            "No documents yet.": "Aún no hay documentos.",
            "No pages scanned.": "No hay páginas escaneadas.",
            "No recent documents": "No hay documentos recientes",
            "No text found.": "No se encontró texto.",
            "Notifications Placeholder": "Notificaciones",
            "Onboarding Preferences": "Preferencias de inicio",
            "Overview": "Descripción general",
            "Personal Details": "Detalles personales",
            "Please use your secure university email.": "Utilice su correo electrónico universitario seguro.",
            "Primary Language": "Idioma principal",
            "Privacy Policy Placeholder": "Política de privacidad",
            "Profile": "Perfil",
            "Recent": "Reciente",
            "Retake": "Volver a tomar",
            "Return to Documents": "Volver a documentos",
            "Review": "Revisar",
            "Review Income Box": "Revisar casilla de ingresos",
            "Scan Photo": "Escanear foto",
            "Scanned Page Placeholder": "Página escaneada",
            "Scanned Pages": "Páginas escaneadas",
            "Sign Up": "Regístrate",
            "Start Guided Review": "Iniciar revisión guiada",
            "Start Scanning": "Comenzar a escanear",
            "Support & Privacy": "Soporte y privacidad",
            "These preferences are used to customize which document fields are highlighted for you natively.": "Estas preferencias se utilizan para personalizar qué campos del documento se resaltan para usted de forma nativa.",
            "This helps us understand the forms you'll be scanning.": "Esto nos ayuda a entender los formularios que escaneará.",
            "This is a standard form used for tax purposes. You need to verify boxes 1, 2, and 5 before submitting.": "Este es un formulario estándar utilizado para fines fiscales. Debe verificar las casillas 1, 2 y 5 antes de enviarlo.",
            "Turn confusing paperwork into clear, step-by-step guidance. Simply scan a document, and we'll help you fill it out.": "Convierta el papeleo confuso en una guía clara paso a paso. Simplemente escanee un documento y lo ayudaremos a completarlo.",
            "Turn confusing paperwork into step-by-step guidance": "Convierta el papeleo confuso en una guía paso a paso",
            "Upload from Camera Roll": "Subir desde el carrete",
            "Uploading & Analyzing...": "Subiendo y analizando...",
            "Verify Email": "Verificar correo electrónico",
            "We've tailored FormFriend to your preferences. You are ready to start scanning.": "Hemos adaptado FormFriend a sus preferencias. Está listo para comenzar a escanear.",
            "Welcome Back": "Bienvenido de nuevo",
            "Welcome to FormFriend": "Bienvenido a FormFriend",
            "What language do you prefer to read in?": "¿En qué idioma prefiere leer?",
            "Where do you live?": "¿Dónde vives?",
            "You have successfully reviewed all the required steps for this document.": "Ha revisado con éxito todos los pasos requeridos para este documento.",
            "You will need:": "Necesitarás:",
            "You're All Set!": "¡Todo listo!",
            "Home": "Inicio",
            "Your Data Is Safe With Us": "Tus datos están seguros con nosotros",
            "We keep it private": "Mantenemos tu privacidad",
            "We never sell or share your personal information.": "Nunca vendemos ni compartimos tu información personal.",
            "Your device, your docs": "Tu dispositivo, tus documentos",
            "Your documents stay on your device unless you choose otherwise.": "Tus documentos permanecen en tu dispositivo a menos que elijas lo contrario.",
            "Locked down tight": "Bien protegido",
            "All data is encrypted and stored securely.": "Todos los datos están cifrados y almacenados de forma segura."
        ],
        "French": [
            "Account Security": "Sécurité du compte",
            "Account details": "Détails du compte",
            "Action Steps": "Étapes à suivre",
            "App Settings": "Paramètres de l'application",
            "Begin Scan": "Commencer le scan",
            "Cancel": "Annuler",
            "Captured Image": "Image capturée",
            "Change Password Placeholder": "Changer le mot de passe",
            "Confirm & Login": "Confirmer et se connecter",
            "Continue": "Continuer",
            "Create Account": "Créer un compte",
            "Document Complete!": "Document terminé !",
            "Documents": "Documents",
            "Don't have an account? Sign Up": "Vous n'avez pas de compte ? Inscrivez-vous",
            "Done": "Terminé",
            "English": "Anglais",
            "Spanish": "Espagnol",
            "French": "Français",
            "Mandarin": "Mandarin",
            "Arabic": "Arabe",
            "Executing Analysis...": "Analyse en cours...",
            "Extracted Text": "Texte extrait",
            "FormFriend": "FormFriend",
            "Get Started": "Commencer",
            "Government Form • 3 Pages": "Formulaire gouvernemental • 3 Pages",
            "Guided View": "Vue guidée",
            "Help & FAQ Placeholder": "Aide et FAQ",
            "Line up the page inside the frame": "Alignez la page dans le cadre",
            "Log In": "Se connecter",
            "Log Out": "Se déconnecter",
            "Log in to FormFriend to continue": "Connectez-vous à FormFriend pour continuer",
            "Make sure the amount listed in Box 1 matches your final pay stub for the year.": "Assurez-vous que le montant indiqué dans la case 1 correspond à votre dernier bulletin de paie de l'année.",
            "Next Step": "Étape suivante",
            "No documents yet.": "Aucun document pour le moment.",
            "No pages scanned.": "Aucune page numérisée.",
            "No recent documents": "Aucun document récent",
            "No text found.": "Aucun texte trouvé.",
            "Notifications Placeholder": "Notifications",
            "Onboarding Preferences": "Préférences d'intégration",
            "Overview": "Aperçu",
            "Personal Details": "Informations personnelles",
            "Please use your secure university email.": "Veuillez utiliser votre adresse e-mail universitaire sécurisée.",
            "Primary Language": "Langue principale",
            "Privacy Policy Placeholder": "Politique de confidentialité",
            "Profile": "Profil",
            "Recent": "Récent",
            "Retake": "Reprendre",
            "Return to Documents": "Retour aux documents",
            "Review": "Vérifier",
            "Review Income Box": "Vérifier la case de revenus",
            "Scan Photo": "Scanner une photo",
            "Scanned Page Placeholder": "Page numérisée",
            "Scanned Pages": "Pages numérisées",
            "Sign Up": "S'inscrire",
            "Start Guided Review": "Commencer la révision guidée",
            "Start Scanning": "Commencer à scanner",
            "Support & Privacy": "Support et confidentialité",
            "These preferences are used to customize which document fields are highlighted for you natively.": "Ces préférences sont utilisées pour personnaliser les champs de document mis en évidence pour vous nativement.",
            "This helps us understand the forms you'll be scanning.": "Cela nous aide à comprendre les formulaires que vous allez scanner.",
            "This is a standard form used for tax purposes. You need to verify boxes 1, 2, and 5 before submitting.": "Ceci est un formulaire standard utilisé à des fins fiscales. Vous devez vérifier les cases 1, 2 et 5 avant de soumettre.",
            "Turn confusing paperwork into clear, step-by-step guidance. Simply scan a document, and we'll help you fill it out.": "Transformez la paperasse confuse en un guide clair, étape par étape. Scannez simplement un document et nous vous aiderons à le remplir.",
            "Turn confusing paperwork into step-by-step guidance": "Transformez la paperasse confuse en guide étape par étape",
            "Upload from Camera Roll": "Importer depuis la pellicule",
            "Uploading & Analyzing...": "Téléchargement et analyse...",
            "Verify Email": "Vérifier l'e-mail",
            "We've tailored FormFriend to your preferences. You are ready to start scanning.": "Nous avons adapté FormFriend à vos préférences. Vous êtes prêt à commencer à scanner.",
            "Welcome Back": "Bon retour",
            "Welcome to FormFriend": "Bienvenue sur FormFriend",
            "What language do you prefer to read in?": "Dans quelle langue préférez-vous lire ?",
            "Where do you live?": "Où habitez-vous ?",
            "You have successfully reviewed all the required steps for this document.": "Vous avez vérifié avec succès toutes les étapes requises pour ce document.",
            "You will need:": "Vous aurez besoin de :",
            "You're All Set!": "Vous êtes prêt !",
            "Home": "Accueil",
            "Your Data Is Safe With Us": "Vos données sont en sécurité avec nous",
            "We keep it private": "Nous protégeons votre vie privée",
            "We never sell or share your personal information.": "Nous ne vendons ni ne partageons vos informations personnelles.",
            "Your device, your docs": "Votre appareil, vos documents",
            "Your documents stay on your device unless you choose otherwise.": "Vos documents restent sur votre appareil sauf si vous en décidez autrement.",
            "Locked down tight": "Verrouillé et sécurisé",
            "All data is encrypted and stored securely.": "Toutes les données sont chiffrées et stockées en toute sécurité."
        ]
    ]
    
    func translate(_ key: String) -> String {
        guard currentLanguage != "English" else { return key }
        let trimmedKey = key.trimmingCharacters(in: .whitespacesAndNewlines)
        return translations[currentLanguage]?[trimmedKey] ?? key
    }
}

extension String {
    func localized() -> String {
        return LanguageManager.shared.translate(self)
    }
}
