openai:
  api-key: ${OPENAI_API_KEY}

aws:
  s3:
    bucket: ${S3_BUCKET}
  cognito:
    user-pool-id: ${COGNITO_USER_POOL_ID}
    client-id: ${COGNITO_CLIENT_ID}
    client-secret: ${COGNITO_CLIENT_SECRET}
    user-pool-uri: ${COGNITO_USER_POOL_URI}

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: demo

  mvc:
    problemdetails:
      enabled: true
    throw-exception-if-no-handler-found: true

  datasource:
    url: ${DATABASE_URI}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
            scope:
              - phone
              - openid
              - email
            # Spring Security by default uses a redirect-uri in the format: {baseUrl}/login/oauth2/code/{registrationId}
            # For example: http://localhost:8080/login/oauth2/code/cognito
            # See more: https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-sample-redirect-uri
            redirect-uri: https://api.formfriend.xyz/login/oauth2/code/cognito
        provider:
          cognito:
            issuer-uri: ${COGNITO_ISSUER_URI}
            jwk-set-uri: ${COGNITO_JWK_SET_URI}
      resourceserver:
        jwt:
          jwk-set-uri: ${COGNITO_JWK_SET_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,heapdump
